feature:
  - head-branch: ['^feat(ure)?[/-].+']
bug:
  - head-branch: ['^fix[/-].+', '^bug[/-].+']
chore:
  - head-branch: ['^chore[/-].+']
refactor:
  - head-branch: ['(refactor|refactoring)[/-].+']
documentation:
  - head-branch: ['doc(umentation)[/-].+']
  - change-files:
    - any-glob-to-any-file: '*.md'
enhancement:
  - head-branch: ['(enhancement|improve)[/-].+']