name: Dev Deploy To Production

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string

jobs:
  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    steps:
      - name: 本番へのデプロイ
        run: |
          echo 開発が実装